version: '3.8'

services:
  # WebDAV server for testing
  webdav:
    image: bytemark/webdav:latest
    container_name: test-webdav
    ports:
      - "8080:80"
    environment:
      - AUTH_TYPE=Basic
      - USERNAME=testuser
      - PASSWORD=testpass
    volumes:
      - webdav-data:/var/lib/dav
    restart: unless-stopped
    networks:
      - test-network

  # MinIO S3-compatible storage for testing
  minio:
    image: minio/minio:latest
    container_name: test-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  webdav-data:
  minio-data: